# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ch1_integration/01_04_ci_for_go
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
    - name: Revive Action
  # You may pin to the exact commit or the version.
  # uses: morphy2k/revive-action@bd8016177e3722fe0aad85e22507805641be5bb1
      uses: morphy2k/revive-action@v2.7.8
          
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
